In [51]:

import numpy as np
import glob2
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from random import randrange
import logging
import random

In [52]:
logging.basicConfig(filename='./log.log',level=10, filemode = 'w', force=True, format='%(asctime)s   %(funcName)s - %(levelname)s:%(message)s')

# Read data

In [53]:
link_cat = r'./PetImages/Cat/**'
link_dog = r'./PetImages/Dog/**'

In [54]:
n_samples = 100
images  = []
labels = []
list_cat = glob2.glob(link_cat)
print(len(list_cat))
for i in range(n_samples):
    if('jpg' in list_cat[i]):
        img = Image.open(list_cat[i]).convert('RGB')
        img = img.resize((400,400), Image.LANCZOS)
        if len(np.array(img).shape)  == 3:
            images.append(np.array(img))
            labels.append(1)
            
list_dog = glob2.glob(link_dog)
print(len(list_dog))
for i in range(n_samples):
    if('jpg' in list_dog[i]):
        img = Image.open(list_dog[i]).convert('RGB')
        img = img.resize((400,400), Image.LANCZOS)
        if len(np.array(img).shape)  == 3:
            images.append(np.array(img))
            labels.append(-1)

X = np.array(images)
y = np.array(labels)

for index in range(len(images)):
    if images[index].shape[2] != 3:
        print(index, images[index].shape[2])

12501
12501


In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [56]:
x_train = np.array([x.flatten() for x in X_train])
x_test = np.array([x.flatten() for x in X_test])

# SVM

In [57]:
y_train

array([ 1, -1,  1,  1, -1, -1,  1,  1, -1, -1,  1, -1,  1,  1,  1,  1, -1,
       -1,  1, -1,  1, -1, -1, -1, -1,  1,  1, -1,  1, -1, -1, -1, -1, -1,
       -1, -1, -1,  1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1,  1, -1, -1,
        1,  1,  1, -1,  1, -1,  1, -1, -1, -1, -1,  1,  1, -1, -1, -1,  1,
       -1, -1,  1,  1, -1,  1,  1, -1,  1, -1, -1,  1,  1,  1, -1, -1, -1,
        1, -1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1,  1,  1,  1,  1, -1, -1,  1, -1,  1, -1, -1,  1,  1,
        1, -1,  1,  1,  1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
        1, -1,  1,  1])

In [67]:
class SVM:
  def __init__(self, C=1.0, gamma=0.1, tol=1e-3, max_iter=1200):
    self.C = C
    self.gamma = gamma
    self.tol = tol
    self.max_iter = max_iter
    self.n_iter = 0
    self.eps = 1e-3

  def rbf(self, x1, x2):
    return np.exp(-self.gamma * (np.linalg.norm(x1 - x2) **2 ))
  
  def output(self, x, X, y, n_samples):
    return np.sum([self.alphas[i] * y[i] * self.rbf(X[i], x) for i in range(n_samples)]) - self.b

  def get_error(self, i, X, y):
    if self.non_bound[i]:
      return self.errors[i]
    else:
      op = self.output(X[i], X, y, self.n_samples) - y[i]
      self.errors[i] = op
      return op  

  def predict(self, X):
    pred = []
    for x in X:
      pred.append(np.sign(self.output(x, self.support_vectors, self.support_vector_labels, self.n_vector)))
    return pred
    
  def compute_L_H(self):
    if self.y1 != self.y2:
      L = max(0, self.alpha2 - self.alpha1)
      H = min(self.C, self.C + self.alpha2 - self.alpha1)
    else:
      L = max(0, self.alpha2 + self.alpha1 - self.C)
      H = min(self.C, self.alpha2 + self.alpha1)
    return L, H
  
  def compute_threshold(self, alpha1_new, alpha2_new, k11, k12, k22):
    b1 = self.E1 + self.y1 * (alpha1_new - self.alpha1) * k11 + \
        self.y2 * (alpha2_new - self.alpha2) * k12 + self.b
    b2 = self.E2 + self.y1 * (alpha1_new - self.alpha1) * k12 + \
        self.y2 * (alpha2_new - self.alpha2) * k22 + self.b

    if 0 < alpha1_new and alpha1_new < self.C:
      return b1
    if 0 < alpha2_new and alpha2_new < self.C:
      return b2
    return (b1 + b2)/2.0
    
  def update_error_cache(self, alpha1_new, alpha2_new, old_b, X):
    delta1 = self.y1 * (alpha1_new - self.alpha1)
    delta2 = self.y2 * (alpha2_new - self.alpha2)
    for i in self.non_bound_idx:
      self.errors[i] += delta1 * self.rbf(self.x1, X[i]) + \
                        delta2 * self.rbf(self.x2, X[i]) + \
                        old_b - self.b

    
  def update_non_bound(self, i1, i2):
    if 0 < self.alphas[i1] and self.alphas[i1] < self.C:
      self.non_bound[i1] = True
      if i1 not in self.non_bound_idx:
        self.non_bound_idx.append(i1)
    else:
      self.non_bound[i1] = False
      if i1 in self.non_bound_idx:
        self.non_bound_idx.remove(i1)
      
    if 0 < self.alphas[i2] and self.alphas[i2] < self.C:
      self.non_bound[i2] = True
      if i2 not in self.non_bound_idx:
        self.non_bound_idx.append(i2)
    else:
      self.non_bound[i2] = False
      if i2 in self.non_bound_idx:
        self.non_bound_idx.remove(i2)

    
  def get_alpha2(self, L, H, k11, k12, k22, s):
    eta = k11 + k22 - 2 * k12
    if eta > 0:
      alpha2_new = self.alpha2 + self.y2 * (self.E1-self.E2)/eta
      alpha2_new = min(H, max(L, alpha2_new))
    else:
      print("ETA < 0")
      logging.error("ETA <= 0")
      f1 = self.y1*(self.E1 + self.b) - self.alpha1*k11 - s*self.alpha2*k12
      f2 = self.y2*(self.E2 + self.b) - s*self.alpha1*k12 - self.alpha2*k22
      L1 = self.alpha1 + s*(self.alpha2-L)
      H1 = self.alpha1 + s*(self.alpha2-H)
      Lobj = L1*f1 + L*f2 + 0.5*(L1**2)*k11 + 0.5*(L**2)*k22 + s*L*L1*k12
      Hobj = H1*f1 + H*f2 + 0.5*(H1**2)*k11 + 0.5*(H**2)*k22 + s*H*H1*k12
      if Lobj < Hobj - self.eps:
        alpha2_new = L
      elif Lobj > Hobj + self.eps:
        alpha2_new = H
      else:
        alpha2_new = self.alpha2
    return alpha2_new
    
  def take_step(self, i1, i2, X, y):
    if i1 == i2:
      return 0
    self.y2 = y[i2]
    self.alpha2 = self.alphas[i2]
    self.x2 = X[i2]
    self.E2 = self.get_error(i2, X, y)
    s = self.y1 * self.y2
    L, H = self.compute_L_H()
    if L==H:
      return 0
    k11 = self.rbf(self.x1, self.x1)
    k12 = self.rbf(self.x1, self.x2)
    k22 = self.rbf(self.x2, self.x2)
    self.alphas[i2] = self.get_alpha2(L, H, k11, k12, k22, s)
    if abs(self.alphas[i2] -self.alpha2) < self.eps * (self.alphas[i2] + self.alpha2 + self.eps):
    # if abs(self.alphas[i2] - self.alpha2) < self.eps: # * (alpha2_new + self.alpha2 + self.eps):
      return 0
    self.alphas[i1] = self.alpha1 + s * (self.alpha2 - self.alphas[i2])
    old_b = self.b
    self.b = self.compute_threshold(self.alphas[i1], self.alphas[i2], k11, k12, k22)
    self.update_non_bound(i1, i2)
    self.update_error_cache(self.alphas[i1], self.alphas[i2], old_b, X)
    logging.warning(f"alpha[{i1}]: {self.alphas[i1]};\talpha[{i2}]: {self.alphas[i2]}") #;\t[{L},  {H}]")
    return 1
  
  def second_choice_heuristic(self, X ,y):
    i2 = -1
    m = 0
    for i in self.non_bound_idx:
      step = abs(self.get_error(i, X, y) - self.E1)
      if step > m:
        m = step
        i2 = i
    return i2

  def examine_example(self, i1, X, y):
    self.y1 = y[i1]
    self.alpha1 = self.alphas[i1]
    self.x1 = X[i1]
    self.E1 = self.get_error(i1, X, y)
    r2 = self.E1 * self.y1
    if (r2 < -self.tol and self.alpha1 < self.C) or \
      (r2 > self.tol and self.alpha1 > 0):
      n_non_bound = len(self.non_bound_idx)
      if (n_non_bound > 1):
        i2 = self.second_choice_heuristic(X, y)
        if i2 != -1:
          if self.take_step(i1, i2, X, y):
            return 1
        
      if n_non_bound > 0:
        rand_i = randrange(n_non_bound)
        for i2 in self.non_bound_idx[rand_i:] + self.non_bound_idx[:rand_i]:
          if self.take_step(i1, i2, X, y):
            return 1
          
      rand_i = randrange(self.n_samples)
      all_indexes = list(range(self.n_samples))
      for i2 in all_indexes[rand_i:] + all_indexes[:rand_i]:
        if self.take_step(i1, i2, X, y):
          return 1
    return 0

  def fit(self, X, y):
    random.seed(42)
    self.n_samples, self.n_features = X.shape
    self.errors = np.zeros(self.n_samples)
    self.alphas = np.zeros(self.n_samples)
    self.non_bound = np.array([False for _ in range(self.n_samples)])
    self.non_bound_idx = []
    self.b = 0
    num_changed = 0
    examine_all = True
    self.n_iter = 0
    while num_changed > 0 or examine_all:
      self.n_iter += 1
      logging.debug(f"N iter: {self.n_iter}")
      logging.debug(f"examine_all: {examine_all}, numchanged: {num_changed}")
      num_changed = 0
      if examine_all:
        for i in range(self.n_samples):
          num_changed += self.examine_example(i, X, y)
      else:
        for i in range(self.n_samples):
          if 0 < self.alphas[i] < self.C:
            num_changed += self.examine_example(i, X, y)
  
      if examine_all:
        examine_all = False
      elif num_changed == 0:
        examine_all = True
        
    sv_idx = (self.alphas > 0)
    logging.info(f"Filtering support vectors, there are {np.sum(sv_idx)} alphas")
    self.support_vectors = X[sv_idx]
    self.support_vector_labels = y[sv_idx]
    self.n_vector = np.sum(sv_idx)
    logging.info("Done fitting")

In [68]:
svm = SVM(gamma = 1/(x_train.shape[1]*x_train.var()))
svm.fit(x_train, y_train)
pred = svm.predict(x_test)
accuracy_score(pred, y_test)

0.4

In [60]:
svm.alphas

array([1.        , 1.        , 1.        , 0.74746624, 1.        ,
       1.        , 1.        , 0.80516838, 1.        , 1.        ,
       0.86705886, 1.        , 0.74145159, 0.97087387, 0.91620691,
       0.95098247, 1.        , 1.        , 0.91638775, 1.        ,
       0.89513098, 1.        , 1.        , 0.94194051, 1.        ,
       0.85217767, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 0.82693439, 0.87285682, 0.90499535,
       1.        , 1.        , 1.        , 1.        , 0.980985  ,
       1.        , 0.9778686 , 0.82254398, 1.        , 1.        ,
       0.87961323, 1.        , 0.90719982, 0.8278083 , 1.        ,
       1.        , 1.        , 0.96655958, 1.        , 0.75319986,
       0.73985618, 1.        , 0.95333773, 1.        , 0.87216141,
       0.99960746, 1.        , 0.90813167, 0.85200661, 1.        ,
       1.        , 1.        , 0.83967082, 0.95720568, 1.        ,
       1.        , 0.81539419, 1.        , 0.82546476, 0.84092

In [61]:
y_train_sklearn = np.array([str(y) for y in y_train])
y_test_sklearn = np.array([str(y) for y in y_test])

svc = SVC(kernel='rbf', gamma = 1/(x_train.shape[1]*x_train.var()))
svc.fit(x_train, y_train_sklearn)
pred = svc.predict(x_test)
accuracy_score(pred, y_test_sklearn)

0.5333333333333333

In [62]:
svc.dual_coef_

array([[-1.        , -0.82843425, -0.5726144 , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -0.8254849 , -0.88337588, -1.        , -1.        ,
        -1.        , -1.        , -1.        , -0.65583543, -1.        ,
        -0.90369915, -0.88973804, -1.        , -1.        , -1.        ,
        -1.        , -1.        , -0.80470053, -1.        , -0.91617143,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -0.9641108 , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -0.98401891, -0.70382414, -0.45512111,
        -0.46591773, -1.        , -0.7201633 , -0.77222499, -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -0.6719186 , -0.45709419, -1.        , -0.5303128 , -1.        ,
        -1.        , -0.95088422,  1.        ,  0.7

In [63]:
class SVM_simplified:
    def __init__(self, C=1.0, gamma=0.1, tol=1e-3, max_iter=1200):
        self.C = C
        self.gamma = gamma
        self.tol = tol
        self.max_iter = max_iter
        self.alphas = None
        self.b = None
        self.support_vectors = None
        self.support_vector_labels = None
        self.n_iter_ = 0

    def rbf_kernel(self, x1, x2):
      return np.exp(-self.gamma * (np.linalg.norm(x1 - x2) ** 2))
    
    def compute_error(self, n_samples, y, i, K):
      err = self.b - y[i]
      for j in range(n_samples):
        err += self.alphas[j] * y[j] * K[j, i]
      return err

    
    def fit(self, X, y):
      # random.seed(42)
      n_samples, n_features = X.shape

      K = np.zeros((n_samples, n_samples))
      for i in range(n_samples):
        for j in range(n_samples):
          K[i,j] = self.rbf_kernel(X[i], X[j])
      
      self.alphas = np.zeros(n_samples)
      self.b = 0
      passes = 0
      while passes < self.max_iter:
        self.n_iter_ += 1
        num_changed_alphas = 0
        for i in range(n_samples):
          Ei = np.sum(self.alphas*y*K[i,:]) + self.b - y[i]
          # Ei = self.compute_error(n_samples, y, i, K)
          # Ei = np.sum(np.dot(np.dot(self.alphas, y), K[i,:])) +self.b - y[i]
          # if abs(ei - Ei)>0.00001:
          #   print(Ei, ei)
          if (((y[i]*Ei < -self.tol) and (self.alphas[i] < self.C)) or ((y[i]*Ei>self.tol) and (self.alphas[i]>0))):
            j = random.choice(list(range(i))+list(range(i+1,n_samples)))
            Ej = np.sum(self.alphas*y*K[j, :]) + self.b - y[j]
            # Ej = self.compute_error(n_samples, y, j, K)
            # Ej = np.sum(np.dot(np.dot(self.alphas, y), K[j,:])) +self.b - y[j]
            alpha_i_old = self.alphas[i]
            alpha_j_old = self.alphas[j]
            if (y[i]!=y[j]):
              L = max(0, self.alphas[j] - self.alphas[i])
              H = min(self.C, self.C + self.alphas[j] - self.alphas[i])
            else:
              L = max(0, self.alphas[i] + self.alphas[j] - self.C)
              H = min(self.C, self.alphas[i] + self.alphas[j])
            if L==H:
              continue
            eta = 2 * K[i,j] - K[i,i] - K[j,j]
            if eta>=0:
              continue
            self.alphas[j] -= y[j]*(Ei-Ej)/eta
            self.alphas[j] = max(L, min(H, self.alphas[j]))

            if (abs(self.alphas[j] - alpha_j_old) < 0.00001):
              continue
            self.alphas[i] += y[i]*y[j]*(alpha_j_old - self.alphas[j])
            
            b1 = self.b - Ei - y[i]*(self.alphas[i]-alpha_i_old)*K[i,i] - y[j]*(self.alphas[j]-alpha_j_old)*K[i,j]
            b2 = self.b - Ej - y[i]*(self.alphas[i]-alpha_i_old)*K[i,j] - y[j]*(self.alphas[j]-alpha_j_old)*K[j,j]
            if (0 < self.alphas[i] and self.alphas[i]<self.C):
              self.b = b1
            elif (0<self.alphas[j] and self.alphas[j]<self.C):
              self.b = b2
            else:
              self.b = (b1 + b2)/2
            num_changed_alphas += 1
        if (num_changed_alphas == 0):
          passes+= 1
        else:
          passes = 0
      sv_idx = (self.alphas>0)
      self.sv_idx = sv_idx
      self.alphas = self.alphas[sv_idx]
      self.support_vectors = X[sv_idx]
      self.support_vector_labels = y[sv_idx]
    def predict(self, X):
      y_pred = np.zeros(len(X))
      for i in range(len(X)):
        s = self.b
        for alpha, sv_y, sv_x in zip(self.alphas, self.support_vector_labels, self.support_vectors):
          s += alpha * sv_y * self.rbf_kernel(X[i], sv_x)
        y_pred[i] = s
      return np.sign(y_pred)

In [64]:
svm = SVM_simplified(gamma = 1/(x_train.shape[1]*x_train.var()))
svm.fit(x_train, y_train)
pred = svm.predict(x_test)
accuracy_score(pred, y_test)

0.7

In [65]:
svm.alphas

array([0.78087783, 1.        , 0.90441755, 1.        , 1.        ,
       1.        , 0.80462725, 0.96789864, 0.97564715, 1.        ,
       0.9533935 , 0.82666611, 1.        , 0.97482102, 0.95767906,
       0.99440895, 0.66167992, 0.93938625, 1.        , 0.98495043,
       0.93323013, 0.80266313, 0.96813827, 1.        , 1.        ,
       1.        , 0.81618037, 1.        , 0.93902046, 1.        ,
       0.81658417, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 0.81195137, 0.95561353, 1.        ,
       0.73565639, 0.96610003, 0.98404775, 0.65788146, 1.        ,
       1.        , 0.86861758, 1.        , 1.        , 0.82392483,
       1.        , 0.948039  , 1.        , 0.84502243, 1.        ,
       1.        , 1.        , 0.91867396, 1.        , 1.        ,
       1.        , 1.        , 0.96081965, 1.        , 0.98849993,
       0.93842456, 0.93855164, 0.73510586, 1.        , 1.        ,
       0.87167585, 0.81594497, 0.93297548, 1.        , 1.     